### ISSUE TITLE
Support react Hooks

### ISSUE THREAD

**Issue by changtimwu** [mimi80417178/shopcart-contextapi#1]
Hi! Mimi:

I think this repo demostrates the usage of context API very well.  

Since you have shown your knowledge of the Hooks API in the code assesssment, could you improve this project with [useContext](   https://reactjs.org/docs/hooks-reference.html#usecontext)?

**Comment by mimi80417178** [comment]
@changtimwu You can see my other project(mimi80417178/FoodShop-only-frontend) that I clearly to  usage by useContext, thank you .
